### ISSUE TITLE
Future of EMS

### ISSUE THREAD

**Issue by mk-pmb** [mogill/ems#25]
Hi! I was shocked to see today that our docs are broken (images + API Documentation + EMS Website) and EMS is going to die for Node.js. I've rather limited funds and I usually avoid C(++), can I help in some other way? Looking at http://syntheticsemantics.com/ it indeed seems it's used mostly by people who know how to set up proper caching. ;-) Or do people just not need the performance anymore and prefer a broker like AMQP instead?

**Comment by mogill** [comment]
My apologies for the apparent abruptness, alas Synthetic Semantics shut down 5 years ago and I stopped maintaining EMS two years ago.  Bit rot is slow, but steady.

I've added some of the missing images from the documentation to the GitHub repo, and tried to update the documentation URLs to use the GitHub images, but I wasn't able to get that to work so I invite you to update the markdown so the images display correctly.

If any files are missing or you have any Q's (other than who uses EMS or for what), I'll do my best to fill in gaps.

**Comment by mogill** [comment]
I don't know how to properly thank you for your efforts getting the documentation better shape than it was.  Which is why I'm humbled to ask again so soon for your help fixing some Travis vs. NPM issue.  All the EMS tests used to pass, but something in the NPM and/or Travis toolchains has changed since the last release and file permissions prevent the tests from running.

With eternal gratitude,

                 -J

**Comment by mk-pmb** [comment]
No problem, I meanwhile found your "Member" badge here seems to be quite an understatement. Thanks for making and maintaining EMS in the first place! I can be glad you provided the world (and most important for me, me ;-) ) with this great technology.

I hope you can afford to maintain it a lot longer, and I wish you best of luck for finding an opportunity and/or helpers to port it to N-API. Meanwhile I'll try to fix Travis. :-)

Have you enabled Github Pages yet and set it to serve the the master branch? Because https://syntheticsemantics.github.io/ems/ still shows 404 for me.

**Comment by mogill** [comment]
I believe all the documentation is up and working on GH & GHP (not so much luck w/NPM, but it's usually the weakest link anyhow), your inspiration and help is greatly appreciated.  Sorting out Travis file permissions is all that's needed to get back to where EMS was two years ago (sigh).

I'm curious why you're so enthusiastic about this six year old Node.js abandonware, any insights you can share with me (jace@mogill.com) would be quite a novelty.

It's easy to scare off potential EMS volunteers: native C/C++, shared memory parallelism, and lack of  users & applications keeps them away.  I'll continue to look, but maybe this is the opportunity you didn't know you were looking for to learn about JS/C++ programming?

**Comment by mk-pmb** [comment]
Sorry for the wait. When I first discovered it, I was impressed by the interop because back then I didn't know I can send JSON over a fifo. Maybe someday it might come in useful for sharing large bitmap graphics between my Webapp and someone's insane ninja GPU monstrosity. Meanwhile it keeps the appeal of a sports car in your urban garage. Being prepared for the moment you discover a reason for driving in Ludicrous Speed. ;-)

**Comment by mogill** [comment]
It looks like we forgot to close this issue.  All the links and images seem to be working now, if you spot any other problems please let me know with a new issue.  Best wishes.   -J
