### ISSUE TITLE
Bug memory leak when used to run custom next.js server.

### ISSUE THREAD

**Issue by wayne-tt** [mogill/ems#29]
We made a custom server for next.js.

and adopted esm using es import and export syntax.

but esm make built pages each request and not free.

So we adopted babel-core & babel-cli to custom server instead of esm.

I hope you will fight with code without suffering.

Good luck!

**Comment by mogill** [comment]
EMS does not dynamically allocate memory from the OS, could you please provide an example that reproduces the problem?  Thanks!

**Comment by wayne-tt** [comment]
When running next js custom server with esm, a code build script is generated for each page request and memory is not free.

I guess this is not an ems problem.

**Comment by mogill** [comment]
Please take a look at the [example of EMS as a web server](https://github.com/mogill/ems/tree/master/Examples/WebServer).  Depending on how you're using EMS in your program you'll want to follow different example operations to get the outcome you're looking for.
